"""
sage - Modular Quality & Completeness Auditor Package for Antigravity (AGY).
"""

__version__ = "0.2.0"

from sage.config import (
    REVIEWER_MODEL,
    REVIEWER_MODEL_SPEC,
    REVIEWER_EFFORT,
    DEFAULT_MODEL_FALLBACKS,
    MAX_ITERATIONS,
    LOG_FILE,
    TURN_DURATION_THRESHOLD,
    TOOL_CALL_THRESHOLD,
    MIN_TOOLS_FOR_DURATION_TRIGGER,
    FILE_EDITING_TOOLS,
    MID_TURN_SAGE_ENABLED,
    SAGE_TOOL_INTERVAL,
    SAGE_TOOL_SCORE_THRESHOLD,
    DEFAULT_TOOL_WEIGHTS,
    get_tool_weight,
    MAX_MID_TURN_STEERS,
    GATEWAY_NOTIFY_INTERVAL,
)
from sage.models import (
    parse_model_version,
    model_sort_key,
    get_available_models,
    resolve_model_candidates,
    cache_working_model,
    get_cached_working_model,
)
from sage.locking import (
    acquire_conversation_lock,
    release_lock,
    log_audit,
    safe_id,
    atomic_write_json,
    cleanup_stale_tmp_files,
)
from sage.guards import (
    check_payload_and_lifecycle,
    evaluate_turn_triggers,
    fail_safe_exit,
    format_hook_message,
    is_post_invocation,
    is_steering_message,
    is_subagent_payload,
    is_subagent_session,
)
from sage.events import (
    EVENT_FINAL_STOP,
    EVENT_HEARTBEAT,
    EVENT_TOOL_THRESHOLD,
    EVENT_ERROR_LOOP,
    EVENT_SENSITIVE_TOOL,
    EVENT_STALE_TASK,
    format_summon_message,
)
from sage.transcript import (
    calculate_turn_tool_score,
    clean_user_prompt,
    extract_session_and_turn_data,
    get_active_background_tasks,
    get_active_subagents,
    get_active_turn_identity,
    get_transcript_path,
    has_active_background_tasks,
    has_active_subagents,
    has_new_user_activity,
    is_post_invocation_completion_candidate,
)
from sage.git import get_git_diff, resolve_workspace_root
from sage.executor import clean_resume_history
from sage.sage import (
    evaluate_mid_turn_progress,
    get_or_create_sage_session,
    run_sage_model,
    save_sage_session,
)
from sage.session_state import (
    record_sage_recap,
    save_session_state,
)
from sage.runner import main

__all__ = [
    "REVIEWER_MODEL",
    "REVIEWER_MODEL_SPEC",
    "REVIEWER_EFFORT",
    "DEFAULT_MODEL_FALLBACKS",
    "MAX_ITERATIONS",
    "LOG_FILE",
    "TURN_DURATION_THRESHOLD",
    "TOOL_CALL_THRESHOLD",
    "MIN_TOOLS_FOR_DURATION_TRIGGER",
    "FILE_EDITING_TOOLS",
    "MID_TURN_SAGE_ENABLED",
    "SAGE_TOOL_INTERVAL",
    "SAGE_TOOL_SCORE_THRESHOLD",
    "DEFAULT_TOOL_WEIGHTS",
    "get_tool_weight",
    "calculate_turn_tool_score",
    "MAX_MID_TURN_STEERS",
    "GATEWAY_NOTIFY_INTERVAL",
    "parse_model_version",
    "model_sort_key",
    "get_available_models",
    "resolve_model_candidates",
    "cache_working_model",
    "get_cached_working_model",
    "acquire_conversation_lock",
    "release_lock",
    "log_audit",
    "safe_id",
    "atomic_write_json",
    "cleanup_stale_tmp_files",
    "fail_safe_exit",
    "format_hook_message",
    "is_post_invocation",
    "is_steering_message",
    "is_subagent_payload",
    "is_subagent_session",
    "get_transcript_path",
    "clean_user_prompt",
    "extract_session_and_turn_data",
    "get_active_background_tasks",
    "get_active_subagents",
    "get_active_turn_identity",
    "has_active_background_tasks",
    "has_active_subagents",
    "has_new_user_activity",
    "is_post_invocation_completion_candidate",
    "get_git_diff",
    "resolve_workspace_root",
    "clean_resume_history",
    "evaluate_mid_turn_progress",
    "get_or_create_sage_session",
    "run_sage_model",
    "save_sage_session",
    "check_payload_and_lifecycle",
    "evaluate_turn_triggers",
    "record_sage_recap",
    "save_session_state",
    "format_summon_message",
    "EVENT_FINAL_STOP",
    "EVENT_HEARTBEAT",
    "EVENT_TOOL_THRESHOLD",
    "EVENT_ERROR_LOOP",
    "EVENT_SENSITIVE_TOOL",
    "EVENT_STALE_TASK",
    "main",
]
